### ISSUE TITLE
datepicker crashes after page rendering

### ISSUE THREAD

**Issue by ANJANS** [robsontenorio/mary#826]
### maryUI version

2.x-dev

### daisyUI version

5.0.9

### Livewire version

3.6

### What browsers are affected?

Chrome

### What happened?

https://github.com/user-attachments/assets/9059f359-f45a-4ce3-92ca-fd787be799d7

**Comment by ANJANS** [comment]
I added wire:ignore to the component, then everything works.

```
` {{-- INPUT --}}
                                <div wire:ignore
                                    x-data="{instance: undefined}"
                                    x-init="instance = flatpickr($refs.input, {{ $setup() }});"
                                    @if(isset($config["mode"]) && $config["mode"] == "range" && $attributes->get('live'))
                                        @change="const value = $event.target.value; if(value.split('to').length == 2) { $wire.set('{{ $modelName() }}', value) };"
                                    @endif
                                    x-on:livewire:navigating.window="instance.destroy();"
                                    class="w-full"
                                >
                                    <input
                                        x-ref="input"
                                        {{
                                            $attributes
                                                ->merge(['type' => 'date'])
                                        }}
                                    />
                                </div>
```

**Comment by ANJANS** [comment]
Datepicker in model calendar is open and not data.

![Image](https://github.com/user-attachments/assets/8a3aa866-5f43-4e9d-862e-1fcb37aabe21)

**Comment by ANJANS** [comment]
I upgrade existing maryUI project from V1 to V2.

**Comment by nubinter** [comment]
Is it fixed in stable release?

**Comment by robsontenorio** [comment]
@LucaSilva-r 2.0.1?

**Comment by LucaSilva-r** [comment]
I think so, I just did another compose update/upgrade just to be safe but it still shows the same behaviour 🤔

**Comment by LucaSilva-r** [comment]
Ok that fixed it. Thank you!
